-- MySQL Script generated by MySQL Workbench
-- 07/15/15 10:51:16
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema exsa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema exsa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `exsa` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `exsa` ;

-- -----------------------------------------------------
-- Table `exsa`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exsa`.`usuarios` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(250) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  `estado` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exsa`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exsa`.`menu` (
  `idMenu` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(250) NOT NULL,
  `url1` VARCHAR(250) NOT NULL,
  `url2` VARCHAR(250) NOT NULL,
  `estado` INT(1) NOT NULL DEFAULT 1,
  `idUsuario` INT NOT NULL,
  `main` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idMenu`),
  INDEX `fk_menu_usuarios1_idx` (`idUsuario` ASC),
  CONSTRAINT `fk_menu_usuarios1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `exsa`.`usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exsa`.`item_menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exsa`.`item_menu` (
  `idItemMenu` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(250) NOT NULL,
  `url1` VARCHAR(250) NOT NULL,
  `url2` VARCHAR(250) NOT NULL,
  `orden` INT NOT NULL,
  `estado` INT(1) NOT NULL,
  `tipo` INT NOT NULL DEFAULT 1,
  `idMenu` INT NOT NULL,
  `imagen` MEDIUMTEXT NULL,
  PRIMARY KEY (`idItemMenu`),
  INDEX `fk_item_menu_menu1_idx` (`idMenu` ASC),
  CONSTRAINT `fk_item_menu_menu1`
    FOREIGN KEY (`idMenu`)
    REFERENCES `exsa`.`menu` (`idMenu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exsa`.`pagina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exsa`.`pagina` (
  `idPagina` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(250) NOT NULL,
  `url1` VARCHAR(250) NOT NULL,
  `url2` VARCHAR(250) NOT NULL,
  `estado` INT NOT NULL DEFAULT 1,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idPagina`),
  INDEX `fk_pagina_usuarios1_idx` (`idUsuario` ASC),
  CONSTRAINT `fk_pagina_usuarios1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `exsa`.`usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exsa`.`imagenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exsa`.`imagenes` (
  `idImagen` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(250) NOT NULL,
  `url` VARCHAR(250) NOT NULL,
  `alt` VARCHAR(250) NOT NULL,
  `estado` INT NOT NULL DEFAULT 1,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idImagen`),
  INDEX `fk_imagenes_usuarios1_idx` (`idUsuario` ASC),
  CONSTRAINT `fk_imagenes_usuarios1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `exsa`.`usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exsa`.`contenido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exsa`.`contenido` (
  `idContenido` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(250) NULL,
  `subTitulo` VARCHAR(250) NULL,
  `texto` MEDIUMTEXT NOT NULL,
  `estado` INT NOT NULL DEFAULT 1,
  `link` INT NOT NULL DEFAULT 0,
  `urlLink` VARCHAR(250) NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idContenido`),
  INDEX `fk_contenido_usuarios1_idx` (`idUsuario` ASC),
  CONSTRAINT `fk_contenido_usuarios1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `exsa`.`usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exsa`.`imagenes_contenidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exsa`.`imagenes_contenidos` (
  `idImagen` INT NOT NULL,
  `idContenido` INT NOT NULL,
  INDEX `fk_imagenes_contenidos_imagenes1_idx` (`idImagen` ASC),
  INDEX `fk_imagenes_contenidos_contenido1_idx` (`idContenido` ASC),
  CONSTRAINT `fk_imagenes_contenidos_imagenes1`
    FOREIGN KEY (`idImagen`)
    REFERENCES `exsa`.`imagenes` (`idImagen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_imagenes_contenidos_contenido1`
    FOREIGN KEY (`idContenido`)
    REFERENCES `exsa`.`contenido` (`idContenido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exsa`.`item_menu_pagina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exsa`.`item_menu_pagina` (
  `idItemMenu` INT NOT NULL,
  `idPagina` INT NOT NULL,
  INDEX `fk_item_menu_pagina_item_menu1_idx` (`idItemMenu` ASC),
  INDEX `fk_item_menu_pagina_pagina1_idx` (`idPagina` ASC),
  CONSTRAINT `fk_item_menu_pagina_item_menu1`
    FOREIGN KEY (`idItemMenu`)
    REFERENCES `exsa`.`item_menu` (`idItemMenu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_menu_pagina_pagina1`
    FOREIGN KEY (`idPagina`)
    REFERENCES `exsa`.`pagina` (`idPagina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exsa`.`pagina_has_contenido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exsa`.`pagina_has_contenido` (
  `idPagina` INT NOT NULL,
  `idContenido` INT NOT NULL,
  PRIMARY KEY (`idPagina`, `idContenido`),
  INDEX `fk_pagina_has_contenido_contenido1_idx` (`idContenido` ASC),
  INDEX `fk_pagina_has_contenido_pagina1_idx` (`idPagina` ASC),
  CONSTRAINT `fk_pagina_has_contenido_pagina1`
    FOREIGN KEY (`idPagina`)
    REFERENCES `exsa`.`pagina` (`idPagina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pagina_has_contenido_contenido1`
    FOREIGN KEY (`idContenido`)
    REFERENCES `exsa`.`contenido` (`idContenido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exsa`.`formularios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exsa`.`formularios` (
  `idFormulario` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(250) NOT NULL,
  `claseFormulario` VARCHAR(45) NOT NULL,
  `estado` INT NOT NULL DEFAULT 1,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idFormulario`),
  INDEX `fk_formularios_usuarios1_idx` (`idUsuario` ASC),
  CONSTRAINT `fk_formularios_usuarios1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `exsa`.`usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exsa`.`elementos_formulario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exsa`.`elementos_formulario` (
  `idElementoFormulario` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idElementoFormulario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exsa`.`campos_formulario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exsa`.`campos_formulario` (
  `idCampoFormulario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `idCampo` VARCHAR(45) NOT NULL,
  `claseCampo` VARCHAR(45) NOT NULL,
  `placeholder` VARCHAR(45) NULL,
  `longitud` INT NULL,
  `idElementoFormulario` INT NOT NULL,
  `orden` INT NULL,
  `idFormulario` INT NOT NULL,
  PRIMARY KEY (`idCampoFormulario`),
  INDEX `fk_campos_formulario_elementos_formulario1_idx` (`idElementoFormulario` ASC),
  INDEX `fk_campos_formulario_formularios1_idx` (`idFormulario` ASC),
  CONSTRAINT `fk_campos_formulario_elementos_formulario1`
    FOREIGN KEY (`idElementoFormulario`)
    REFERENCES `exsa`.`elementos_formulario` (`idElementoFormulario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_campos_formulario_formularios1`
    FOREIGN KEY (`idFormulario`)
    REFERENCES `exsa`.`formularios` (`idFormulario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exsa`.`contenido_formulario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exsa`.`contenido_formulario` (
  `idContenido` INT NOT NULL,
  `idFormulario` INT NOT NULL,
  INDEX `fk_contenido_formulario_contenido1_idx` (`idContenido` ASC),
  INDEX `fk_contenido_formulario_formularios1_idx` (`idFormulario` ASC),
  CONSTRAINT `fk_contenido_formulario_contenido1`
    FOREIGN KEY (`idContenido`)
    REFERENCES `exsa`.`contenido` (`idContenido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contenido_formulario_formularios1`
    FOREIGN KEY (`idFormulario`)
    REFERENCES `exsa`.`formularios` (`idFormulario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exsa`.`archivos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exsa`.`archivos` (
  `idArchivo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(250) NOT NULL,
  `ruta` MEDIUMTEXT NOT NULL,
  `tamano` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `estado` INT NOT NULL DEFAULT 1,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idArchivo`),
  INDEX `fk_archivos_usuarios1_idx` (`idUsuario` ASC),
  CONSTRAINT `fk_archivos_usuarios1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `exsa`.`usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exsa`.`contenido_archivos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exsa`.`contenido_archivos` (
  `idContenido` INT NOT NULL,
  `idArchivo` INT NOT NULL,
  INDEX `fk_contenido_archivos_archivos1_idx` (`idArchivo` ASC),
  INDEX `fk_contenido_archivos_contenido1_idx` (`idContenido` ASC),
  CONSTRAINT `fk_contenido_archivos_archivos1`
    FOREIGN KEY (`idArchivo`)
    REFERENCES `exsa`.`archivos` (`idArchivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contenido_archivos_contenido1`
    FOREIGN KEY (`idContenido`)
    REFERENCES `exsa`.`contenido` (`idContenido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exsa`.`menu_has_item_menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exsa`.`menu_has_item_menu` (
  `idItemMenu` INT NOT NULL,
  `idMenu` INT NOT NULL,
  PRIMARY KEY (`idItemMenu`, `idMenu`),
  INDEX `fk_menu_has_item_menu_item_menu1_idx` (`idItemMenu` ASC),
  INDEX `fk_menu_has_item_menu_menu1_idx` (`idMenu` ASC),
  CONSTRAINT `fk_menu_has_item_menu_menu1`
    FOREIGN KEY (`idMenu`)
    REFERENCES `exsa`.`menu` (`idMenu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_menu_has_item_menu_item_menu1`
    FOREIGN KEY (`idItemMenu`)
    REFERENCES `exsa`.`item_menu` (`idItemMenu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exsa`.`tabs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exsa`.`tabs` (
  `idTab` INT NOT NULL AUTO_INCREMENT,
  `id` VARCHAR(45) NOT NULL,
  `class` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL DEFAULT '1',
  PRIMARY KEY (`idTab`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exsa`.`panel_tab`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exsa`.`panel_tab` (
  `nombre` VARCHAR(50) NOT NULL,
  `contenido` MEDIUMTEXT NOT NULL,
  `estado` VARCHAR(45) NOT NULL DEFAULT '1',
  `idTab` INT NOT NULL,
  INDEX `fk_panel_tab_tabs1_idx` (`idTab` ASC),
  CONSTRAINT `fk_panel_tab_tabs1`
    FOREIGN KEY (`idTab`)
    REFERENCES `exsa`.`tabs` (`idTab`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exsa`.`contenido_has_tabs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exsa`.`contenido_has_tabs` (
  `idContenido` INT NOT NULL,
  `idTab` INT NOT NULL,
  PRIMARY KEY (`idContenido`, `idTab`),
  INDEX `fk_contenido_has_tabs_tabs1_idx` (`idTab` ASC),
  INDEX `fk_contenido_has_tabs_contenido1_idx` (`idContenido` ASC),
  CONSTRAINT `fk_contenido_has_tabs_contenido1`
    FOREIGN KEY (`idContenido`)
    REFERENCES `exsa`.`contenido` (`idContenido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contenido_has_tabs_tabs1`
    FOREIGN KEY (`idTab`)
    REFERENCES `exsa`.`tabs` (`idTab`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exsa`.`valores_select`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exsa`.`valores_select` (
  `valor` VARCHAR(50) NOT NULL,
  `texto` VARCHAR(250) NOT NULL,
  `idCampoFormulario` INT NOT NULL,
  INDEX `fk_valores_select_campos_formulario1_idx` (`idCampoFormulario` ASC),
  CONSTRAINT `fk_valores_select_campos_formulario1`
    FOREIGN KEY (`idCampoFormulario`)
    REFERENCES `exsa`.`campos_formulario` (`idCampoFormulario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
